region: us-east-1
metrics:
  - aws_namespace: AWS/Billing
    aws_metric_name: EstimatedCharges
    aws_dimensions: [Currency]
    aws_statistics: [Maximum]
    range_seconds: 86400
    period_seconds: 3600