global:
    scrape_interval: 15s
  
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
  
    - job_name: 'dcgm-exporter'
      static_configs:
        - targets: ['dcgm-exporter:9400']
  
    - job_name: 'cloudwatch-exporter'
      static_configs:
        - targets: ['cloudwatch-exporter:9106']