global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']

  # Uncomment the following if you enable the dcgm-exporter container
  # - job_name: 'dcgm-exporter'
  #   static_configs:
  #     - targets: ['dcgm-exporter:9400']